Warehouse-MS/Warehouse-MS/Models/Warehouse.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Warehouse_MS.Auth.Models;

namespace Warehouse_MS.Models
{
    public class Warehouse
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SizeInUnit { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }

        //ForeignKey
        public ApplicationUser ApplicationUser { get; set; }
        [ForeignKey("ApplicationUser")]
        public string UserId { get; set; }

        //Navigation properties
        public List<Storage> Storages { get; set; }
    }
}

Warehouse-MS/Warehouse-MS/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Warehouse_MS.Models;
using Warehouse_MS.Models.DTO;
using Warehouse_MS.Models.Interfaces;

namespace Warehouse_MS.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly IWarehouse _warehouse;

        public WarehouseController(IWarehouse Warehouse)
        {
            this._warehouse = Warehouse;
        }


        public async Task<ActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            IEnumerable<WarehouseDto> Warehouses = await _warehouse.GetUserWarehouse(userId);
            return View(Warehouses);
        }

        public async Task<ActionResult<WarehouseDto>> Details(int id)
        {
            WarehouseDto warehouse = await _warehouse.GetWarehouse(id);

            return View(warehouse);
        }

        public async Task<ActionResult<Warehouse>> Edit(int id)
        {
            WarehouseDto warehouseDto = await _warehouse.GetWarehouse(id);
                Warehouse warehouse = new Warehouse
                {
                    Id = warehouseDto.Id,
                    Name = warehouseDto.Name,
                    Description = warehouseDto.Description,
                    SizeInUnit = warehouseDto.SizeInUnit,
                    Location = warehouseDto.Location,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
                };
            return View(warehouse);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, Warehouse warehouse)
        {
            await _warehouse.UpdateWarehouse(id, warehouse);

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(WarehouseDto warehouse)
        {

            if (ModelState.IsValid)
            {
                Warehouse newwarehouse = new Warehouse
                {
                    Id = warehouse.Id,
                    Name = warehouse.Name,
                    Description = warehouse.Description,
                    SizeInUnit = warehouse.SizeInUnit,
                    Location = warehouse.Location,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier)

                };

                await _warehouse.Create(newwarehouse);
                return RedirectToAction("Index");
            }

            return View(warehouse);
        }

        public async Task<ActionResult> Delete(int id)
        {
            await _warehouse.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

Warehouse-MS/Warehouse-MS/Views/Warehouse/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Warehouse_MS.Models.Warehouse
@{
    Layout = "_layout";
}


<div class="container-xxl flex-grow-1 container-p-y">
            <div class="card mb-4">
              <h5 class="card-header">Create Warehouse</h5>
              <hr class="my-0" />
              <div class="card-body">
                <form asp-controller="Warehouse" asp-action="Create" method="post">
                  <div class="row">
                    <div class="mb-3 col-md-6">
                      <label for="firstName" class="form-label">Name</label>
                      <input type="text"
                      class="form-control"
                      id="basic-icon-default-fullname"
                      placeholder="Name"
                      aria-label="Name"
                      aria-describedby="basic-icon-default-fullname2"
                      asp-for="@Model.Name" />
                    </div>
                    <div class="mb-3 col-md-6">
                            <label class="form-label" for="country">Location</label>
                            <select asp-for="@Model.Location" id="country" class="select2 form-select">
                              <option value="">Select</option>
                              <option  value="Amman">Amman</option>
                              <option value="Irbid">Irbid</option>
                              <option value="Zarqa">Zarqa</option>
                              <option value="Mafraq">Mafraq</option>
                              <option value="Ajloun">Ajloun</option>
                              <option value="Jerash">Jerash</option>
                              <option value="Madaba">Madaba</option>
                              <option value="Balqa">Balqa</option>
                              <option value="Karak">Karak</option>
                              <option value="Tafileh">Tafileh</option>
                              <option value="Maan">Maan</option>
                              <option value="Aqaba">Aqaba</option>
                            </select>
                          </div>
                    <div class="mb-3 col-md-6">
                      <label for="basic-icon-default-company" class="form-label">Description</label>
                      <input type="text"
                                           id="basic-icon-default-company"
                                           class="form-control"
                                           placeholder="Description"
                                           aria-label="Description"
                                           aria-describedby="basic-icon-default-company2"
                                           asp-for="@Model.Description" />
                    </div>
                    <div class="mb-3 col-md-6">
                      <label for="organization" class="form-label">Size In Unit</label>
                      <input type="number"
                                           id="basic-icon-default-phone"
                                           class="form-control phone-mask"
                                           placeholder="SizeInUnit"
                                           aria-label="SizeInUnit"
                                           aria-describedby="basic-icon-default-phone2"
                                           asp-for="@Model.SizeInUnit" />
                    </div>
                  </div>
                  <div class="mt-2">
                    <button type="submit" class="btn btn-primary me-2">Save changes</button>
                    <a href="/warehouse/index" class="btn btn-outline-secondary">Cancel</a>
                  </div>
                  </form>
                </div>
              </div>
            
          </div>

Warehouse-MS/Warehouse-MS/Views/Warehouse/Details.cshtml
@using Warehouse_MS.Models.DTO
@model WarehouseDto
@{
    Layout = "_Layout";
}
@if (Model.Storages.Count == 0)
{
    <div class="text-center">

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="misc-wrapper">
                <h2 class="mb-2 mx-2">Opps! No storage found</h2>
                <p class="mb-4 mx-2">It's ok you can easily go there and create new storage for your warehouse</p>
                <a href="/storage/create" class="btn btn-primary">Add storage</a>
                <div class="mt-4">
                  <img
                    src="../assets/img/illustrations/girl-doing-yoga-light.png"
                    alt="girl-doing-yoga-light"
                    width="500"
                    class="img-fluid"
                    data-app-dark-img="../illustrations/girl-doing-yoga-dark.png"
                    data-app-light-img="../illustrations/girl-doing-yoga-light.png"
                  />
                </div>
              </div>
            </div>
          </div>
}
else
{
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
            <div class="col">
            <div class="col" style="display: block;overflow: auto;">
                <div class="card" style="background-color: inherit;">
                    <div class="card-body">
                    <h5 class="text-center">Add Storage</h5>
                    </div>
                    <div class="card-body">
                        <div class="col text-center">
                            <a type="button" href="/Storage/create?id=@Model.Id" class="btn bi-plus btn-icon ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16"> <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/> <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/> </svg>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            @foreach (var item in Model.Storages)
            {
                <div class="col">
                    <div class="col">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title">@item.Name</h5>
                                <h6 class="card-subtitle text-muted">@item.LocationInWarehouse</h6>
                            </div>
                            <div class="card-body">
                                <p class="card-text">@item.Description</p>
                                <p class="card-text">@item.SizeInUnit</p>
                                <a class="btn btn-primary" href="/Storage/Details?id=@item.Id">Details</a>
                                <a class="btn btn-primary"  href="/Storage/Edit?id=@item.Id">Edit</a>
                                <a class="btn btn-danger" href="/Storage/Delete?id=@item.Id">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
 }

Warehouse-MS/Warehouse-MS/Views/Warehouse/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Warehouse_MS.Models.Warehouse
@{
    Layout = "_Layout";
}
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="card mb-4">
      <h5 class="card-header">Edit Warehouse</h5>
      <hr class="my-0" />
      <div class="card-body">
        <form asp-controller="Warehouse" asp-action="Edit" method="post">
            <input hidden asp-for="@Model.Id" />
            <input hidden asp-for="@Model.UserId" />
          <div class="row">
            <div class="mb-3 col-md-6">
              <label for="basic-icon-default-fullname" class="form-label">Name</label>
              <input type="text"
              class="form-control"
              id="basic-icon-default-fullname"
              placeholder="Name"
              aria-label="Name"
              aria-describedby="basic-icon-default-fullname2"
              asp-for="Name" />
            </div>
            <div class="mb-3 col-md-6">
                    <label class="form-label" for="country">Location</label>
                    <select asp-for="@Model.Location" id="country" class="select2 form-select">
                      <option value="">Select</option>
                      <option  value="Amman">Amman</option>
                      <option value="Irbid">Irbid</option>
                      <option value="Zarqa">Zarqa</option>
                      <option value="Mafraq">Mafraq</option>
                      <option value="Ajloun">Ajloun</option>
                      <option value="Jerash">Jerash</option>
                      <option value="Madaba">Madaba</option>
                      <option value="Balqa">Balqa</option>
                      <option value="Karak">Karak</option>
                      <option value="Tafileh">Tafileh</option>
                      <option value="Maan">Maan</option>
                      <option value="Aqaba">Aqaba</option>
                    </select>
                  </div>
            <div class="mb-3 col-md-6">
              <label for="basic-icon-default-company" class="form-label">Description</label>
              <input type="text"
                                   id="basic-icon-default-company"
                                   class="form-control"
                                   placeholder="Description"
                                   aria-label="Description"
                                   aria-describedby="basic-icon-default-company2"
                                   asp-for="@Model.Description" />
            </div>
            <div class="mb-3 col-md-6">
              <label for="organization" class="form-label">Size In Unit</label>
              <input type="number"
                                   id="basic-icon-default-phone"
                                   class="form-control phone-mask"
                                   placeholder="SizeInUnit"
                                   aria-label="SizeInUnit"
                                   aria-describedby="basic-icon-default-phone2"
                                   asp-for="@Model.SizeInUnit" />
            </div>
          </div>
          <div class="mt-2">
            <button type="submit" class="btn btn-primary me-2">Save changes</button>
            <a href="/warehouse/index" class="btn btn-outline-secondary">Cancel</a>
          </div>
          </form>
        </div>
      </div>
    
  </div>



 

Warehouse-MS/Warehouse-MS/Views/Warehouse/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Warehouse_MS.Models.DTO
@model List<WarehouseDto>
@{
    Layout = "_Layout";
}
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
        <div class="col">
            <div class="col" style="display: block;overflow: auto;">
                <div class="card" style="background-color: inherit;">
                    <div class="card-body">
                    <h5 class="text-center">Add Warehouse</h5>
                    </div>
                    <div class="card-body">
                        <div class="col text-center">
                            <a type="button" asp-controller="Warehouse" asp-action="Create" class="btn bi-plus btn-icon ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16"> <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/> <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/> </svg>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <h6 class="card-subtitle text-muted">@item.Location</h6>
                        </div>
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <a class="btn btn-primary" href="/Warehouse/Details?id=@item.Id">Details</a>
                            <a class="btn btn-primary" href="/Warehouse/Edit?id=@item.Id">Edit</a>
                            <a class="btn btn-danger" href="/Warehouse/Delete?id=@item.Id">Delete</a>                          
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Warehouse-MS/Warehouse-MS/Views/Warehouse/_WarehouseFields.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Warehouse_MS.Models.Warehouse
    <label>
        <span>Name</span>
    </label>
    <br />
    <input asp-for="Name"/>
    @Html.ValidationMessageFor(x => x.Name)
    <br />
    <label>
        <span>Description</span>
    </label>
    <br />
    <input asp-for="@Model.Description"/>
    <br />
    <br />  
    <label>
        <span>Location</span>
    </label>
    <br />
    <input asp-for="@Model.Location"/>
    <br />
    <br />
      <label>
        <span>SizeInUnit</span>
    </label>
    <br />
    <input asp-for="@Model.SizeInUnit"/>
    <br />
    <br />