Warehouse-MS/Warehouse-MS/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Warehouse_MS.Models;
using Warehouse_MS.Models.Interfaces;

namespace Warehouse_MS.Controllers
{
    public class ProductTypeController : Controller
    {
        private readonly IProductType _productType;

        public ProductTypeController(IProductType productType)
        {
            this._productType = productType;
        }

        // GET: api/ProductTypes
        
        public async Task<ActionResult> Index()
        {
             IEnumerable < ProductType > productType = await _productType.GetProductTypes();
            return View(productType);
        }

        // GET: api/ProductType/5
       
        public async Task<ActionResult> Details(int id)
        {
            ProductType productType = await _productType.GetProductType(id);
            if (productType == null)
            {
                return View("Error");
            }
            return View(productType);
        }
        public async Task<IActionResult> goEditView(int id)
        {
            ProductType productType = await _productType.GetProductType(id);
            if (productType == null)
            {
                return View("Error");
            }
            ViewBag.flagReqType = "Edit";
            return View("Edit", productType);
        }
        public async Task<IActionResult> goAddView()
        {
            ViewBag.flagReqType = "add";


            return View("Add");
        }


        // PUT: api/ProductType/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ProductType productType)
        {
            if (id != productType.Id)
            {
                return View("Error");
            }
            ProductType newProductType = await _productType.UpdateProductType(id, productType);

            return View(newProductType);
        }

        // POST: api/ProductType
        [HttpPost]
        public async Task<ActionResult<ProductType>> Add(ProductType productType)
        {
            ProductType newProductType = await _productType.Create(productType);
            return View(newProductType);

        }

        // DELETE: api/ProductType/5
      
        public async Task<IActionResult> Delete(int id)
        {
            ProductType productType = await _productType.GetProductType(id);
            if (productType == null)
            {
                return View("Error");
            }
            await _productType.Delete(id);
            return Redirect("/");

        }

    }
}

Warehouse-MS/Warehouse-MS/Views/ProductType/Add.cshtml
@model Warehouse_MS.Models.ProductType
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}

    @*var x = "";
                if (ViewBag.flagReqType == "add") {
            <h3>wellcome in add page</h3>
                    x = "Add";
                } else {
        <h3>wellcome in add page</h3>
                    x = "Edit";
                }}

            <form asp-controller="ProductType" asp-action=@x method="post">
                @{
                    if (x == "Edit")
                    {
                        <input hidden asp-for="@Model.Id" />
                    }
                }

                <partial name="_AddEdit"></partial>
                <button type="submit"> @x Product Type</button>
            </form>
            <div asp-validation-summary="All"></div>*@


    <div class="container-xxl flex-grow-2 container-p-y">
        <div class="container-xxl">
            <div class="authentication-wrapper authentication-basic container-p-y">
                <div class="authentication-inner">
                    <!-- Register -->
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <h4 class="mb-2">Add Product Type</h4>
                            </div>
                            <form asp-controller="ProductType" asp-action="Add" method="post">





                                <div class="mb-3">
                                    <label class="form-label" for="basic-icon-default-fullname"> Name</label>
                                    <div class="input-group input-group-merge">
                                        <span id="basic-icon-default-fullname2" class="input-group-text">

                                            <i class='bx bx-home-alt'></i>
                                        </span>
                                        <input type="text"
                                               class="form-control"
                                               id="basic-icon-default-fullname"
                                               placeholder="Name"
                                               aria-label="Name"
                                               aria-describedby="basic-icon-default-fullname2"
                                               asp-for="Name" />
                                        @Html.ValidationMessageFor(x => x.Name)

                                    </div>
                                </div>

                                <div class="mb-3">
                                    <label class="form-label" for="basic-icon-default-company">Description</label>
                                    <div class="input-group input-group-merge">
                                        <span id="basic-icon-default-company2" class="input-group-text">
                                            <i class='bx bxs-detail'></i>
                                        </span>
                                        <input type="text"
                                               id="basic-icon-default-company"
                                               class="form-control"
                                               placeholder="Description"
                                               aria-label="Description"
                                               aria-describedby="basic-icon-default-company2"
                                               asp-for="@Model.Description" />
                                    </div>
                                </div>





                                <div class="container">
                                    <div class="row">
                                        <div class="col text-center">
                                            <button class="btn btn-primary w-50" type="submit">Add</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Warehouse-MS/Warehouse-MS/Views/ProductType/Details.cshtml

@model Warehouse_MS.Models.ProductType
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Empty";
}
@{
    ViewData["Title"] = "ProductType "+@Model.Name;
}

<a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="goAddView"> Add new ProductType </a>
<br />

@*//// To fromat tha product data as bootstrap card*@
<section style="background-color: #eee;">
    <div class="card mb-3" style="max-width: 450px;">
        <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
             data-mdb-ripple-color="light">
            @*<img style="height: 350px" src=@Model.ImageUri*@

            <a href="#!">
                <div class="mask">
                    <div class="d-flex justify-content-start align-items-end h-100"></div>
                </div>
                <div class="hover-overlay">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </div>
            </a>
        </div>
        <div class="card-body">

            <h5 class="card-title mb-3">@Model.Name</h5>


            <h6 class="mb-3">@Model.Description</h6>


            <a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="goEditView" asp-route-id=@Model.Id>update</a>
            <a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="Delete" asp-route-id=@Model.Id> delete </a>

        </div>
    </div>
</section>

Warehouse-MS/Warehouse-MS/Views/ProductType/Edit.cshtml
@model Warehouse_MS.Models.ProductType
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@*<div class="form-outline mb-4">
        <label class="form-label" for="form3Example3"> StorageType Name</label>

        <input asp-for="@Model.Name" type="text" class="form-control form-control-lg" />
    </div>

    <div class="form-outline mb-4">
        <label class="form-label" for="form3Example3"> Description </label>

        <input asp-for="@Model.Description" type="text" class="form-control form-control-lg" />
    </div>*@

<div class="container-xxl flex-grow-2 container-p-y">
    <div class="container-xxl">
        <div class="authentication-wrapper authentication-basic container-p-y">
            <div class="authentication-inner">
                <!-- Register -->
                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            <h4 class="mb-2">Edit Product Type</h4>
                        </div>
                        <form asp-controller="ProductType" asp-action="Edit" method="post">


                            <input hidden asp-for="@Model.Id" />


                            <div class="mb-3">
                                <label class="form-label" for="basic-icon-default-fullname"> Name</label>
                                <div class="input-group input-group-merge">
                                    <span id="basic-icon-default-fullname2" class="input-group-text">

                                        <i class='bx bx-home-alt'></i>
                                    </span>
                                    <input type="text"
                                           class="form-control"
                                           id="basic-icon-default-fullname"
                                           placeholder="Name"
                                           aria-label="Name"
                                           aria-describedby="basic-icon-default-fullname2"
                                           asp-for="Name" />
                                    @Html.ValidationMessageFor(x => x.Name)

                                </div>
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="basic-icon-default-company">Description</label>
                                <div class="input-group input-group-merge">
                                    <span id="basic-icon-default-company2" class="input-group-text">
                                        <i class='bx bxs-detail'></i>
                                    </span>
                                    <input type="text"
                                           id="basic-icon-default-company"
                                           class="form-control"
                                           placeholder="Description"
                                           aria-label="Description"
                                           aria-describedby="basic-icon-default-company2"
                                           asp-for="@Model.Description" />
                                </div>
                            </div>





                            <div class="container">
                                <div class="row">
                                    <div class="col text-center">
                                        <button class="btn btn-primary w-50" type="submit">Edit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Warehouse-MS/Warehouse-MS/Views/ProductType/Index.cshtml
@model IEnumerable<Warehouse_MS.Models.ProductType>
@using Warehouse_MS.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}

@*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    @{
        ViewData["Title"] = "ProductType Page";
    }



    <h1 class="mt-4 mb-5"><strong>All ProductType</strong></h1>
    <a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="Index"> Back </a>
    <a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="goAddView"> Add new ProductType </a>
    <br />*@



<br />

@if (TempData["AlertMessage"] != null)
{
<div class="alert alert-primary" role="alert">
    <strong>Thank You ! </strong>@TempData["AlertMessage"]

</div>
}
<br />

@*<section style="background-color: #eee;">
    <div class="text-center container py-5">

        <div class="row">
            @foreach (ProductType productType in Model)
            {
              
<section style="background-color: #eee;">
                    <div class="card mb-3" style="max-width: 450px;">
                        <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                             data-mdb-ripple-color="light">

                            <a href="#!">
                                <div class="mask">
                                    <div class="d-flex justify-content-start align-items-end h-100"></div>
                                </div>
                                <div class="hover-overlay">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </div>
                            </a>
                        </div>
                        <div class="card-body">

                            <h5 class="card-title mb-3">@productType.Name</h5>


                            <h6 class="mb-3">@productType.Description</h6>


                            <a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="goEditView" asp-route-id=@productType.Id>update</a>
                            <a class="btn btn-primary btn-lg " asp-controller="ProductType" asp-action="Delete" asp-route-id=@productType.Id> delete </a>

                        </div>
                    </div>
                </section>


            }


        </div>
    </div>
</section>*@






<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-5" style="height:20rem;">
        @foreach (ProductType productType in Model)
        {
            <div class="col">
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">@productType.Name</h5>
                            <h6 class="card-subtitle text-muted">@productType.Description</h6>
                        </div>
                        <div class="card-body">


                            <a class="btn btn-primary" href="/ProductType/goEditView?id=@productType.Id">Edit</a>
                            <a class="btn btn-danger" href="/ProductType/Delete?id=@productType.Id">Delete</a>



                        </div>
                    </div>
                </div>
            </div>

        }

        <div class="col">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center">Add Product Type</h5>

                    </div>
                    <div class="card-body">
                        <div class="col text-center">

                            <a type="button" href="/ProductType/goaddview" class="btn bi-plus btn-icon ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                </svg>
                            </a>


                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>





